version: '3.7'
services:
  server:
    image: benlumia007/mysql
    container_name: server
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "1025:1025"
      - "8025:8025"